name: Deploy GeoImóveis

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Build Site
        run: |
          # Força a criação do index.html se necessário
          if [ ! -f index.html ]; then
            echo '<!DOCTYPE html><html><body><h1>GeoImóveis RS/SC</h1><p>Site em construção</p></body></html>' > index.html
          fi
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
